# Generated by Django 3.0.3 on 2020-03-25 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127, verbose_name='Полное имя')),
                ('nickname', models.CharField(blank=True, max_length=127, verbose_name='Никнейм')),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], default=2, verbose_name='Гендер')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('about', models.TextField(blank=True, verbose_name='Об актере')),
            ],
            options={
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актеры',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network_type', models.PositiveIntegerField(choices=[(1, 'Другое'), (2, 'Твиттер'), (3, 'Вк'), (4, 'Телеграмм'), (5, 'Тнстаграм')], default=1, verbose_name='соц. сеть')),
                ('name', models.CharField(blank=True, max_length=127)),
                ('url', models.URLField(max_length=127, verbose_name='сслка')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='core.Artist', verbose_name='артист')),
            ],
            options={
                'verbose_name': 'Соц. сеть',
                'verbose_name_plural': 'Соц. сети',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Оригинальное название')),
                ('relise', models.DateField(verbose_name='Релиз')),
                ('about', models.TextField(blank=True, verbose_name='О кино')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='сслка')),
                ('artists', models.ManyToManyField(to='core.Artist', verbose_name='Артисты')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
